- hosts: node00
  gather_facts: true
  vars:
    my_name: Lola

  vars_prompt:
    name: user
    prompt: Enter Username
    private: no
    
  tasks:
    - apt:
        pkg: apache2
        state: installed
      when: ansible_distribution == "Ubuntu"
    
    - yum:
        pkg: httpd
        state: installed
      when: ansible_distribution == "RedHat"

    - yum:
        pkg: httpd
        state: installed
      when: ansible_distribution == "Amazon"


