- hosts: node00
  gather_facts: true
  vars:
    my_name: Lola

- vars_prompt:
    - name: username
      prompt: What is your username?
      private: no
    - name: password
      prompt: What is your password?
    
    - name: Display myname
      debug:
      var: hostvars[inventory_hostname]

- hosts: all
  name: Setting up the hostnames
  tasks:
  - hostname: name="{{ inventory_hostname }}"
    become: yes