---
- hosts: webservers
  become: true
  tasks:
  - name: Install default-jdk
    yum: name=java-1.8.0-openjdk 
    state = installed
  
  - name: Install mlocate 
    package: name={{item}} state=installed
    with_items:
    - mlocate
    - strace
    - git
    - php

  - name: New Folder
    file:
      path: /home/ec2-user/{{ item }}
      state: directory
    with_items:
    - yelp
    - google
    - apple
    - yahoo
    - allstate