---
- hosts: webservers
  become: true
  tasks:
  - name: Install package
    yum: 
      pkg: {{item}} 
      state: installed
    with_items:
      - mlocate
      - strace
      - git
      - php
      - java-1.8.0-openjdk 

  - name: New Folder
    file:
      path: /home/ec2-user/{{ item }}
      state: directory
    with_items:
    - yelp
    - google
    - apple
    - yahoo
    - allstate