- hosts: node00
  gather_facts: false

  tasks:
  - name: packages
    yum:
      pkg: {{ item }}
      state: installed
    with_items:
    - mlocate
    - strace
    - java8
    - php5

  - name: folders
    file:
      path: /home/ec2-user/{{ item }}
      state: directory
    with_items:
    - yelp
    - google
    - apple
    - yahoo
    - allstate