---
- hosts: webservers
  become: true
  tasks:
  - name: Install default-jdk
    yum: name=java-1.8.0-openjdk state=present
  
  - name: Install mlocate (RHEL)
    package: name={{item}} state=latest
    with_items:
    - mlocate
    - strace
    - git
    - php5
