- hosts: web
  become: true

  tasks:
  - name: install JDK
    yum:
    name: jre-1.8.0-openjdk

  - name: extract tomcat 
    unarchive:
    src: /usr/local/apache-tomcat-9.0.50.tar.gz
    dest: /usr/local
    remote_src: yes

  - name: start tomcat 
  shell: nohup /usr/local/apache-tomcat-9.0.50/bin/startup.sh